import { DefinicionCampoFormulario } from "../pages/form.page";

export const configuracionFormularios: Record<string, DefinicionCampoFormulario[]> = {
  "EN - Embed - Tipo 3 - Bachelor - Program select": [
    {
      nombre: "Nombres",
      selector: 'input[name="FirstName"]',
      tipo: "text",
      valor: "Ñoño",
      validacion: {
        muestrasInvalidas: ["Omni123", "Omni213!@#", "@ / \\ ? ! # % $ * + ' : ;  () [] {}"],
      },
      placeholderEsperado: "First Name *",
    },
    {
      nombre: "Apellidos",
      selector: 'input[name="MiddleName"]',
      tipo: "text",
      valor: "Pérez",
      validacion: {
        muestrasInvalidas: ["Omni123", "Omni213!@#", "@ / \\ ? ! # % $ * + ' : ;  () [] {}"],
      },
      placeholderEsperado: "Last Name *",
    },
    {
      nombre: "Email",
      selector: 'input[name="Email"]',
      tipo: "email",
      placeholderEsperado: "Email *",
    },
    {
      nombre: "Tu eres",
      selector: 'select[name="mktoStakeholder"]',
      tipo: "select",
      valor: "Student",
      placeholderEsperado: "You are a *",
    },
    {
      nombre: "Año de preferencia para comenzar",
      selector: 'select[name="ie_estimateddateofadmissiontoie"]',
      tipo: "select",
      placeholderEsperado: "Preferred start year *",
    },
    {
      nombre: "Pais Colombia",
      selector: 'select[name="ie_countryid"]',
      tipo: "select",
      valor: "Colombia",
      placeholderEsperado: "Current Country/Territory of Residence *",
    },
    {
      nombre: "Pais Mexico",
      selector: 'select[name="ie_countryid"]',
      tipo: "select",
      valor: "Mexico",
    },
    {
      nombre: "Genero",
      selector: 'select[name="ie_genderidentity"]',
      tipo: "select",
      placeholderEsperado: "Gender Identity *",
    },
    {
      nombre: "Provincia/Region",
      selector: 'select[name="ie_provinceregionid"]',
      tipo: "select",
      valor: "Aguascalientes",
      placeholderEsperado: "State/Province (Only certain countries) *",
    },
    {
      nombre: "Codigo cedular del pais",
      selector: 'select[name="phoneCountryCode"]',
      tipo: "select",
      valor: "Colombia (+57)",
      placeholderEsperado: "Phone Country Code",
    },
    {
      nombre: "Celular",
      selector: 'input[name="Phone"]',
      tipo: "text",
      valor: "3005005050",
      placeholderEsperado: "Phone Number",
    },
    {
      nombre: "Autorización de IE",
      selector: 'input[name="mkto_gdprc22"]',
      tipo: "checkbox",
    }
  ],
  "ES - Embed - Tipo 3 - Bachelor - Program select": [
    {
      nombre: "Nombres",
      selector: 'input[name="FirstName"]',
      tipo: "text",
      valor: "Ñoño",
      validacion: {
        muestrasInvalidas: ["Omni123", "Omni213!@#", "@ / \\ ? ! # % $ * + ' : ;  () [] {}"],
      },
      placeholderEsperado: "Nombre *",
    },
    {
      nombre: "Apellidos",
      selector: 'input[name="MiddleName"]',
      tipo: "text",
      valor: "Pérez",
      validacion: {
        muestrasInvalidas: ["Omni123", "Omni213!@#", "@ / \\ ? ! # % $ * + ' : ;  () [] {}"],
      },
      placeholderEsperado: "Apellidos *",
    },
    {
      nombre: "Email",
      selector: 'input[name="Email"]',
      tipo: "email",
      placeholderEsperado: "Email *",
    },
    {
      nombre: "Tu eres",
      selector: 'select[name="mktoStakeholder"]',
      tipo: "select",
      valor: "Alumno",
      placeholderEsperado: "Eres un *",
    },
    {
      nombre: "Año de preferencia para comenzar",
      selector: 'select[name="ie_estimateddateofadmissiontoie"]',
      tipo: "select",
      placeholderEsperado: "Año de preferencia para comenzar *",
    },
    {
      nombre: "Pais Colombia",
      selector: 'select[name="ie_countryid"]',
      tipo: "select",
      valor: "Colombia",
      placeholderEsperado: "País/Territorio de residencia actual *",
    },
    {
      nombre: "Pais Mexico",
      selector: 'select[name="ie_countryid"]',
      tipo: "select",
      valor: "Mexico",
    },
    {
      nombre: "Genero",
      selector: 'select[name="ie_genderidentity"]',
      tipo: "select",
      placeholderEsperado: "Identidad de género *",
    },
    {
      nombre: "Provincia/Region",
      selector: 'select[name="ie_provinceregionid"]',
      tipo: "select",
      valor: "Aguascalientes",
      placeholderEsperado: "Estado/Provincia (Sólo algunos países) *",
    },
    {
      nombre: "Codigo cedular del pais",
      selector: 'select[name="phoneCountryCode"]',
      tipo: "select",
      valor: "Colombia (+57)",
      placeholderEsperado: "Código de teléfono",
    },
    {
      nombre: "Celular",
      selector: 'input[name="Phone"]',
      tipo: "text",
      valor: "3005005050",
      placeholderEsperado: "Número de teléfono",
    },
    {
      nombre: "Autorización de IE",
      selector: 'input[name="mkto_gdprc22"]',
      tipo: "checkbox",
    }
  ],
  "EN - Embed - Tipo 3 - Master - Program select optional Phone number": [
    {
      nombre: "Nombres",
      selector: 'input[name="FirstName"]',
      tipo: "text",
      valor: "Ñoño",
      validacion: {
        muestrasInvalidas: ["Omni123", "Omni213!@#", "@ / \\ ? ! # % $ * + ' : ;  () [] {}"],
      },
      placeholderEsperado: "First Name *",
    },
    {
      nombre: "Apellidos",
      selector: 'input[name="MiddleName"]',
      tipo: "text",
      valor: "Pérez",
      validacion: {
        muestrasInvalidas: ["Omni123", "Omni213!@#", "@ / \\ ? ! # % $ * + ' : ;  () [] {}"],
      },
      placeholderEsperado: "Last Name *",
    },
    {
      nombre: "Email",
      selector: 'input[name="Email"]',
      tipo: "email",
      placeholderEsperado: "Email *",
    },
    {
      nombre: "Año de preferencia para comenzar",
      selector: 'select[name="ie_estimateddateofadmissiontoie"]',
      tipo: "select",
      placeholderEsperado: "Planned entry date *",
    },
    {
      nombre: "Pais Colombia",
      selector: 'select[name="ie_countryid"]',
      tipo: "select",
      valor: "Colombia",
      placeholderEsperado: "Current Country/Territory of Residence *",
    },
    {
      nombre: "Pais Mexico",
      selector: 'select[name="ie_countryid"]',
      tipo: "select",
      valor: "Mexico",
    },
    {
      nombre: "Genero",
      selector: 'select[name="ie_genderidentity"]',
      tipo: "select",
      placeholderEsperado: "Gender Identity *",
    },
    {
      nombre: "Provincia/Region",
      selector: 'select[name="ie_provinceregionid"]',
      tipo: "select",
      valor: "Aguascalientes",
      placeholderEsperado: "State/Province (Only certain countries) *",
    },
    {
      nombre: "Autorización de IE",
      selector: 'input[name="mkto_gdprc22"]',
      tipo: "checkbox",
    }
  ],
  "EN - Embed - Tipo 3 - Master - Program select required Phone number": [
    {
      nombre: "Nombres",
      selector: 'input[name="FirstName"]',
      tipo: "text",
      valor: "Ñoño",
      validacion: {
        muestrasInvalidas: ["Omni123", "Omni213!@#", "@ / \\ ? ! # % $ * + ' : ;  () [] {}"],
      },
      placeholderEsperado: "First Name *",
    },
    {
      nombre: "Apellidos",
      selector: 'input[name="MiddleName"]',
      tipo: "text",
      valor: "Pérez",
      validacion: {
        muestrasInvalidas: ["Omni123", "Omni213!@#", "@ / \\ ? ! # % $ * + ' : ;  () [] {}"],
      },
      placeholderEsperado: "Last Name *",
    },
    {
      nombre: "Email",
      selector: 'input[name="Email"]',
      tipo: "email",
      placeholderEsperado: "Email *",
    },
    {
      nombre: "Pais Colombia",
      selector: 'select[name="ie_countryid"]',
      tipo: "select",
      valor: "Colombia",
      placeholderEsperado: "Current Country/Territory of Residence *",
    },
    {
      nombre: "Pais Mexico",
      selector: 'select[name="ie_countryid"]',
      tipo: "select",
      valor: "Mexico",
    },
    {
      nombre: "Genero",
      selector: 'select[name="ie_genderidentity"]',
      tipo: "select",
      placeholderEsperado: "Gender Identity *",
    },
    {
      nombre: "Provincia/Region",
      selector: 'select[name="ie_provinceregionid"]',
      tipo: "select",
      valor: "Aguascalientes",
      placeholderEsperado: "State/Province (Only certain countries) *",
    },
    {
      nombre: "Tu eres",
      selector: 'select[name="mktoStakeholder"]',
      tipo: "select",
      valor: "Student",
      placeholderEsperado: "You are a *",
    },
    {
      nombre: "Año de preferencia para comenzar",
      selector: 'select[name="ie_estimateddateofadmissiontoie"]',
      tipo: "select",
      placeholderEsperado: "Planned entry date *",
    },
    {
      nombre: "Codigo cedular del pais",
      selector: 'select[name="phoneCountryCode"]',
      tipo: "select",
      valor: "Colombia (+57)",
      placeholderEsperado: "Phone Country Code *",
    },
    {
      nombre: "Celular",
      selector: 'input[name="Phone"]',
      tipo: "text",
      valor: "3005005050",
      placeholderEsperado: "Phone Number *",
    },
    {
      nombre: "Autorización de IE",
      selector: 'input[name="mkto_gdprc22"]',
      tipo: "checkbox",
    }
  ],
  "EN - Embed - Tipo 3 - Master - Program select - BAC": [
    {
      nombre: "Nombres",
      selector: 'input[name="FirstName"]',
      tipo: "text",
      valor: "Ñoño",
      validacion: {
        muestrasInvalidas: ["Omni123", "Omni213!@#", "@ / \\ ? ! # % $ * + ' : ;  () [] {}"],
      },
      placeholderEsperado: "First Name *",
    },
    {
      nombre: "Apellidos",
      selector: 'input[name="MiddleName"]',
      tipo: "text",
      valor: "Pérez",
      validacion: {
        muestrasInvalidas: ["Omni123", "Omni213!@#", "@ / \\ ? ! # % $ * + ' : ;  () [] {}"],
      },
      placeholderEsperado: "Last Name *",
    },
    {
      nombre: "Email",
      selector: 'input[name="Email"]',
      tipo: "email",
      placeholderEsperado: "Email *",
    },
    {
      nombre: "Pais Colombia",
      selector: 'select[name="ie_countryid"]',
      tipo: "select",
      valor: "Colombia",
      placeholderEsperado: "Current Country/Territory of Residence *",
    },
    {
      nombre: "Pais Mexico",
      selector: 'select[name="ie_countryid"]',
      tipo: "select",
      valor: "Mexico",
    },
    {
      nombre: "Genero",
      selector: 'select[name="ie_genderidentity"]',
      tipo: "select",
      placeholderEsperado: "Gender Identity *",
    },
    {
      nombre: "Provincia/Region",
      selector: 'select[name="ie_provinceregionid"]',
      tipo: "select",
      valor: "Aguascalientes",
      placeholderEsperado: "State/Province (Only certain countries) *",
    },

    {
      nombre: "Codigo cedular del pais",
      selector: 'select[name="phoneCountryCode"]',
      tipo: "select",
      valor: "Colombia (+57)",
      placeholderEsperado: "Phone Country Code *",
    },
    {
      nombre: "Celular",
      selector: 'input[name="Phone"]',
      tipo: "text",
      valor: "3005005050",
      placeholderEsperado: "Phone Number *",
    },
    {
      nombre: "Año de preferencia para comenzar",
      selector: 'select[name="ie_estimateddateofadmissiontoie"]',
      tipo: "select",
      placeholderEsperado: "Planned entry date *",
    },
    {
      nombre: "Autorización de IE",
      selector: 'input[name="mkto_gdprc22"]',
      tipo: "checkbox",
    }
  ],
  "EN - Embed - Tipo 3 - Master - Program select - Whatsapp": [
    {
      nombre: "Nombres",
      selector: 'input[name="FirstName"]',
      tipo: "text",
      valor: "Ñoño",
      validacion: {
        muestrasInvalidas: ["Omni123", "Omni213!@#", "@ / \\ ? ! # % $ * + ' : ;  () [] {}"],
      },
      placeholderEsperado: "First Name *",
    },
    {
      nombre: "Apellidos",
      selector: 'input[name="MiddleName"]',
      tipo: "text",
      valor: "Pérez",
      validacion: {
        muestrasInvalidas: ["Omni123", "Omni213!@#", "@ / \\ ? ! # % $ * + ' : ;  () [] {}"],
      },
      placeholderEsperado: "Last Name *",
    },
    {
      nombre: "Email",
      selector: 'input[name="Email"]',
      tipo: "email",
      placeholderEsperado: "Email *",
    },
    {
      nombre: "Pais Colombia",
      selector: 'select[name="ie_countryid"]',
      tipo: "select",
      valor: "Colombia",
      placeholderEsperado: "Current Country/Territory of Residence *",
    },
    {
      nombre: "Pais Mexico",
      selector: 'select[name="ie_countryid"]',
      tipo: "select",
      valor: "Mexico",
    },
    {
      nombre: "Genero",
      selector: 'select[name="ie_genderidentity"]',
      tipo: "select",
      placeholderEsperado: "Gender Identity *",
    },
    {
      nombre: "Provincia/Region",
      selector: 'select[name="ie_provinceregionid"]',
      tipo: "select",
      valor: "Aguascalientes",
      placeholderEsperado: "State/Province (Only certain countries) *",
    },
    {
      nombre: "Codigo cedular del pais",
      selector: 'select[name="phoneCountryCode"]',
      tipo: "select",
      valor: "Colombia (+57)",
      placeholderEsperado: "Phone Country Code *",
    },
    {
      nombre: "Celular",
      selector: 'input[name="Phone"]',
      tipo: "text",
      valor: "3005005050",
      placeholderEsperado: "Phone Number *",
    },
    {
      nombre: "Año de preferencia para comenzar",
      selector: 'select[name="ie_estimateddateofadmissiontoie"]',
      tipo: "select",
      placeholderEsperado: "Planned entry date *",
    },
    {
      nombre: "Autorización de IE",
      selector: 'input[name="mkto_gdprc22"]',
      tipo: "checkbox",
    }
  ],
  "ES - Embed - Tipo 3 - Master - Program select with optional Phone number": [
    {
      nombre: "Nombres",
      selector: 'input[name="FirstName"]',
      tipo: "text",
      valor: "Ñoño",
      validacion: {
        muestrasInvalidas: ["Omni123", "Omni213!@#", "@ / \\ ? ! # % $ * + ' : ;  () [] {}"],
      },
      placeholderEsperado: "Nombre *",
    },
    {
      nombre: "Apellidos",
      selector: 'input[name="MiddleName"]',
      tipo: "text",
      valor: "Pérez",
      validacion: {
        muestrasInvalidas: ["Omni123", "Omni213!@#", "@ / \\ ? ! # % $ * + ' : ;  () [] {}"],
      },
      placeholderEsperado: "Apellidos *",
    },
    {
      nombre: "Email",
      selector: 'input[name="Email"]',
      tipo: "email",
      placeholderEsperado: "Email *",
    },
    {
      nombre: "Pais Colombia",
      selector: 'select[name="ie_countryid"]',
      tipo: "select",
      valor: "Colombia",
      placeholderEsperado: "País/Territorio de residencia actual *",
    },
    {
      nombre: "Pais Mexico",
      selector: 'select[name="ie_countryid"]',
      tipo: "select",
      valor: "Mexico",
    },
    {
      nombre: "Genero",
      selector: 'select[name="ie_genderidentity"]',
      tipo: "select",
      placeholderEsperado: "Identidad de género *",
    },
    {
      nombre: "Provincia/Region",
      selector: 'select[name="ie_provinceregionid"]',
      tipo: "select",
      valor: "Aguascalientes",
      placeholderEsperado: "Estado/Provincia (Sólo algunos países) *",
    },
    {
      nombre: "Año de preferencia para comenzar",
      selector: 'select[name="ie_estimateddateofadmissiontoie"]',
      tipo: "select",
      placeholderEsperado: "¿Cuándo planeas comenzar tus estudios? *",
    },
    {
      nombre: "Autorización de IE",
      selector: 'input[name="mkto_gdprc22"]',
      tipo: "checkbox",
    }
  ],
  "ES - Embed - Tipo 3 - Master - Program select with required Phone number": [
    {
      nombre: "Nombres",
      selector: 'input[name="FirstName"]',
      tipo: "text",
      valor: "Ñoño",
      validacion: {
        muestrasInvalidas: ["Omni123", "Omni213!@#", "@ / \\ ? ! # % $ * + ' : ;  () [] {}"],
      },
      placeholderEsperado: "Nombre *",
    },
    {
      nombre: "Apellidos",
      selector: 'input[name="MiddleName"]',
      tipo: "text",
      valor: "Pérez",
      validacion: {
        muestrasInvalidas: ["Omni123", "Omni213!@#", "@ / \\ ? ! # % $ * + ' : ;  () [] {}"],
      },
      placeholderEsperado: "Apellidos *",
    },
    {
      nombre: "Email",
      selector: 'input[name="Email"]',
      tipo: "email",
      placeholderEsperado: "Email *",
    },
    {
      nombre: "Pais Colombia",
      selector: 'select[name="ie_countryid"]',
      tipo: "select",
      valor: "Colombia",
      placeholderEsperado: "País/Territorio de residencia actual *",
    },
    {
      nombre: "Pais Mexico",
      selector: 'select[name="ie_countryid"]',
      tipo: "select",
      valor: "Mexico",
    },
    {
      nombre: "Genero",
      selector: 'select[name="ie_genderidentity"]',
      tipo: "select",
      placeholderEsperado: "Identidad de género *",
    },
    {
      nombre: "Provincia/Region",
      selector: 'select[name="ie_provinceregionid"]',
      tipo: "select",
      valor: "Aguascalientes",
      placeholderEsperado: "Estado/Provincia (Sólo algunos países) *",
    },
    {
      nombre: "Tu eres",
      selector: 'select[name="mktoStakeholder"]',
      tipo: "select",
      valor: "Alumno",
      placeholderEsperado: "Eres un *",
    },
    {
      nombre: "Año de preferencia para comenzar",
      selector: 'select[name="ie_estimateddateofadmissiontoie"]',
      tipo: "select",
      placeholderEsperado: "¿Cuándo planeas comenzar tus estudios? *",
    },
    {
      nombre: "Codigo cedular del pais",
      selector: 'select[name="phoneCountryCode"]',
      tipo: "select",
      valor: "Colombia (+57)",
      placeholderEsperado: "Código de teléfono *",
    },
    {
      nombre: "Celular",
      selector: 'input[name="Phone"]',
      tipo: "text",
      valor: "3005005050",
      placeholderEsperado: "Número de teléfono *",
    },
    {
      nombre: "Autorización de IE",
      selector: 'input[name="mkto_gdprc22"]',
      tipo: "checkbox",
    }
  ],
  "ES - Embed - Tipo 3 - Master - Program select - BAC": [
    {
      nombre: "Nombres",
      selector: 'input[name="FirstName"]',
      tipo: "text",
      valor: "Ñoño",
      validacion: {
        muestrasInvalidas: ["Omni123", "Omni213!@#", "@ / \\ ? ! # % $ * + ' : ;  () [] {}"],
      },
      placeholderEsperado: "Nombre *",
    },
    {
      nombre: "Apellidos",
      selector: 'input[name="MiddleName"]',
      tipo: "text",
      valor: "Pérez",
      validacion: {
        muestrasInvalidas: ["Omni123", "Omni213!@#", "@ / \\ ? ! # % $ * + ' : ;  () [] {}"],
      },
      placeholderEsperado: "Apellidos *",
    },
    {
      nombre: "Email",
      selector: 'input[name="Email"]',
      tipo: "email",
      placeholderEsperado: "Email *",
    },
    {
      nombre: "Pais Colombia",
      selector: 'select[name="ie_countryid"]',
      tipo: "select",
      valor: "Colombia",
      placeholderEsperado: "País/Territorio de residencia actual *",
    },
    {
      nombre: "Pais Mexico",
      selector: 'select[name="ie_countryid"]',
      tipo: "select",
      valor: "Mexico",
    },
    {
      nombre: "Genero",
      selector: 'select[name="ie_genderidentity"]',
      tipo: "select",
      placeholderEsperado: "Identidad de género *",
    },
    {
      nombre: "Provincia/Region",
      selector: 'select[name="ie_provinceregionid"]',
      tipo: "select",
      valor: "Aguascalientes",
      placeholderEsperado: "Estado/Provincia (Sólo algunos países) *",
    },
    {
      nombre: "Tu eres",
      selector: 'select[name="mktoStakeholder"]',
      tipo: "select",
      valor: "Alumno",
      placeholderEsperado: "Eres un *",
    },
    {
      nombre: "Codigo cedular del pais",
      selector: 'select[name="phoneCountryCode"]',
      tipo: "select",
      valor: "Colombia (+57)",
      placeholderEsperado: "Código de teléfono *",
    },
    {
      nombre: "Celular",
      selector: 'input[name="Phone"]',
      tipo: "text",
      valor: "3005005050",
      placeholderEsperado: "Número de teléfono *",
    },
    {
      nombre: "Año de preferencia para comenzar",
      selector: 'select[name="ie_estimateddateofadmissiontoie"]',
      tipo: "select",
      placeholderEsperado: "¿Cuándo planeas comenzar tus estudios? *",
    },
    {
      nombre: "Autorización de IE",
      selector: 'input[name="mkto_gdprc22"]',
      tipo: "checkbox",
    }
  ],
  "ES - Embed - Tipo 3 - Master - Program select - Whatsapp": [
    {
      nombre: "Nombres",
      selector: 'input[name="FirstName"]',
      tipo: "text",
      valor: "Ñoño",
      validacion: {
        muestrasInvalidas: ["Omni123", "Omni213!@#", "@ / \\ ? ! # % $ * + ' : ;  () [] {}"],
      },
      placeholderEsperado: "Nombre *",
    },
    {
      nombre: "Apellidos",
      selector: 'input[name="MiddleName"]',
      tipo: "text",
      valor: "Pérez",
      validacion: {
        muestrasInvalidas: ["Omni123", "Omni213!@#", "@ / \\ ? ! # % $ * + ' : ;  () [] {}"],
      },
      placeholderEsperado: "Apellidos *",
    },
    {
      nombre: "Email",
      selector: 'input[name="Email"]',
      tipo: "email",
      placeholderEsperado: "Email *",
    },
    {
      nombre: "Pais Colombia",
      selector: 'select[name="ie_countryid"]',
      tipo: "select",
      valor: "Colombia",
      placeholderEsperado: "País/Territorio de residencia actual *",
    },
    {
      nombre: "Pais Mexico",
      selector: 'select[name="ie_countryid"]',
      tipo: "select",
      valor: "Mexico",
    },
    {
      nombre: "Genero",
      selector: 'select[name="ie_genderidentity"]',
      tipo: "select",
      placeholderEsperado: "Identidad de género *",
    },
    {
      nombre: "Provincia/Region",
      selector: 'select[name="ie_provinceregionid"]',
      tipo: "select",
      valor: "Aguascalientes",
      placeholderEsperado: "Estado/Provincia (Sólo algunos países) *",
    },
    {
      nombre: "Codigo cedular del pais",
      selector: 'select[name="phoneCountryCode"]',
      tipo: "select",
      valor: "Colombia (+57)",
      placeholderEsperado: "Código de teléfono *",
    },
    {
      nombre: "Celular",
      selector: 'input[name="Phone"]',
      tipo: "text",
      valor: "3005005050",
      placeholderEsperado: "Número de teléfono *",
    },
    {
      nombre: "Año de preferencia para comenzar",
      selector: 'select[name="ie_estimateddateofadmissiontoie"]',
      tipo: "select",
      placeholderEsperado: "¿Cuándo planeas comenzar tus estudios? *",
    },
    {
      nombre: "Autorización de IE",
      selector: 'input[name="mkto_gdprc22"]',
      tipo: "checkbox",
    }
  ],
  "EN - Embed - Tipo 3 - Summer PRE - UNI - Program select with optional Phone  number": [
    {
      nombre: "Nombres",
      selector: 'input[name="FirstName"]',
      tipo: "text",
      valor: "Ñoño",
      validacion: {
        muestrasInvalidas: ["Omni123", "Omni213!@#", "@ / \\ ? ! # % $ * + ' : ;  () [] {}"],
      },
      placeholderEsperado: "First Name *",
    },
    {
      nombre: "Apellidos",
      selector: 'input[name="MiddleName"]',
      tipo: "text",
      valor: "Pérez",
      validacion: {
        muestrasInvalidas: ["Omni123", "Omni213!@#", "@ / \\ ? ! # % $ * + ' : ;  () [] {}"],
      },
      placeholderEsperado: "Last Name *",
    },
    {
      nombre: "Email",
      selector: 'input[name="Email"]',
      tipo: "email",
      placeholderEsperado: "Email *",
    },
    {
      nombre: "Pais Colombia",
      selector: 'select[name="ie_countryid"]',
      tipo: "select",
      valor: "Colombia",
      placeholderEsperado: "Current Country/Territory of Residence *",
    },
    {
      nombre: "Pais Mexico",
      selector: 'select[name="ie_countryid"]',
      tipo: "select",
      valor: "Mexico",
    },
    {
      nombre: "Genero",
      selector: 'select[name="ie_genderidentity"]',
      tipo: "select",
      placeholderEsperado: "Gender Identity *",
    },
    {
      nombre: "Provincia/Region",
      selector: 'select[name="ie_provinceregionid"]',
      tipo: "select",
      valor: "Aguascalientes",
      placeholderEsperado: "State/Province (Only certain countries) *",
    },
    {
      nombre: "Año de preferencia para comenzar",
      selector: 'select[name="ie_estimateddateofadmissiontoie"]',
      tipo: "select",
      placeholderEsperado: "Preferred start year *",
    },
    {
      nombre: "Autorización de IE",
      selector: 'input[name="mkto_gdprc22"]',
      tipo: "checkbox",
    }
  ],
  "EN - Embed - Tipo 3 - Summer UNI - Program select": [
    {
      nombre: "Nombres",
      selector: 'input[name="FirstName"]',
      tipo: "text",
      valor: "Ñoño",
      validacion: {
        muestrasInvalidas: ["Omni123", "Omni213!@#", "@ / \\ ? ! # % $ * + ' : ;  () [] {}"],
      },
      placeholderEsperado: "First Name *",
    },
    {
      nombre: "Apellidos",
      selector: 'input[name="MiddleName"]',
      tipo: "text",
      valor: "Pérez",
      validacion: {
        muestrasInvalidas: ["Omni123", "Omni213!@#", "@ / \\ ? ! # % $ * + ' : ;  () [] {}"],
      },
      placeholderEsperado: "Last Name *",
    },
    {
      nombre: "Email",
      selector: 'input[name="Email"]',
      tipo: "email",
      placeholderEsperado: "Email *",
    },
    {
      nombre: "Pais Colombia",
      selector: 'select[name="ie_countryid"]',
      tipo: "select",
      valor: "Colombia",
      placeholderEsperado: "Current Country/Territory of Residence *",
    },
    {
      nombre: "Pais Mexico",
      selector: 'select[name="ie_countryid"]',
      tipo: "select",
      valor: "Mexico",
    },
    {
      nombre: "Genero",
      selector: 'select[name="ie_genderidentity"]',
      tipo: "select",
      placeholderEsperado: "Gender Identity *",
    },
    {
      nombre: "Provincia/Region",
      selector: 'select[name="ie_provinceregionid"]',
      tipo: "select",
      valor: "Aguascalientes",
      placeholderEsperado: "State/Province (Only certain countries) *",
    },
    {
      nombre: "Codigo cedular del pais",
      selector: 'select[name="phoneCountryCode"]',
      tipo: "select",
      valor: "Colombia (+57)",
      placeholderEsperado: "Phone Country Code *",
    },
    {
      nombre: "Celular",
      selector: 'input[name="Phone"]',
      tipo: "text",
      valor: "3005005050",
      placeholderEsperado: "Phone Number *",
    },
    {
      nombre: "Año de preferencia para comenzar",
      selector: 'select[name="ie_estimateddateofadmissiontoie"]',
      tipo: "select",
      placeholderEsperado: "Planned entry date *",
    },
    {
      nombre: "Autorización de IE",
      selector: 'input[name="mkto_gdprc22"]',
      tipo: "checkbox",
    }
  ],
  "EN - Embed - Tipo 3 - Summer UNI - Especialización select": [
    {
      nombre: "Nombres",
      selector: 'input[name="FirstName"]',
      tipo: "text",
      valor: "Ñoño",
      validacion: {
        muestrasInvalidas: ["Omni123", "Omni213!@#", "@ / \\ ? ! # % $ * + ' : ;  () [] {}"],
      },
      placeholderEsperado: "First Name *",
    },
    {
      nombre: "Apellidos",
      selector: 'input[name="MiddleName"]',
      tipo: "text",
      valor: "Pérez",
      validacion: {
        muestrasInvalidas: ["Omni123", "Omni213!@#", "@ / \\ ? ! # % $ * + ' : ;  () [] {}"],
      },
      placeholderEsperado: "Last Name *",
    },
    {
      nombre: "Email",
      selector: 'input[name="Email"]',
      tipo: "email",
      placeholderEsperado: "Email *",
    },
    {
      nombre: "Pais Colombia",
      selector: 'select[name="ie_countryid"]',
      tipo: "select",
      valor: "Colombia",
      placeholderEsperado: "Current Country/Territory of Residence *",
    },
    {
      nombre: "Pais Mexico",
      selector: 'select[name="ie_countryid"]',
      tipo: "select",
      valor: "Mexico",
    },
    {
      nombre: "Genero",
      selector: 'select[name="ie_genderidentity"]',
      tipo: "select",
      placeholderEsperado: "Gender Identity *",
    },
    {
      nombre: "Provincia/Region",
      selector: 'select[name="ie_provinceregionid"]',
      tipo: "select",
      valor: "Aguascalientes",
      placeholderEsperado: "State/Province (Only certain countries) *",
    },
    {
      nombre: "Codigo cedular del pais",
      selector: 'select[name="phoneCountryCode"]',
      tipo: "select",
      valor: "Colombia (+57)",
      placeholderEsperado: "Phone Country Code *",
    },
    {
      nombre: "Celular",
      selector: 'input[name="Phone"]',
      tipo: "text",
      valor: "3005005050",
      placeholderEsperado: "Phone Number *",
    },
    {
      nombre: "Año de preferencia para comenzar",
      selector: 'select[name="ie_estimateddateofadmissiontoie"]',
      tipo: "select",
      placeholderEsperado: "Preferred start year *",
    },
    {
      nombre: "Autorización de IE",
      selector: 'input[name="mkto_gdprc22"]',
      tipo: "checkbox",
    }
  ],
  "EN - Embed - Tipo 3 - Summer UNI - Program select - BAC": [
    {
      nombre: "Nombres",
      selector: 'input[name="FirstName"]',
      tipo: "text",
      valor: "Ñoño",
      validacion: {
        muestrasInvalidas: ["Omni123", "Omni213!@#", "@ / \\ ? ! # % $ * + ' : ;  () [] {}"],
      },
      placeholderEsperado: "First Name *",
    },
    {
      nombre: "Apellidos",
      selector: 'input[name="MiddleName"]',
      tipo: "text",
      valor: "Pérez",
      validacion: {
        muestrasInvalidas: ["Omni123", "Omni213!@#", "@ / \\ ? ! # % $ * + ' : ;  () [] {}"],
      },
      placeholderEsperado: "Last Name *",
    },
    {
      nombre: "Email",
      selector: 'input[name="Email"]',
      tipo: "email",
      placeholderEsperado: "Email *",
    },
    {
      nombre: "Pais Colombia",
      selector: 'select[name="ie_countryid"]',
      tipo: "select",
      valor: "Colombia",
      placeholderEsperado: "Current Country/Territory of Residence *",
    },
    {
      nombre: "Pais Mexico",
      selector: 'select[name="ie_countryid"]',
      tipo: "select",
      valor: "Mexico",
    },
    {
      nombre: "Genero",
      selector: 'select[name="ie_genderidentity"]',
      tipo: "select",
      placeholderEsperado: "Gender Identity *",
    },
    {
      nombre: "Provincia/Region",
      selector: 'select[name="ie_provinceregionid"]',
      tipo: "select",
      valor: "Aguascalientes",
      placeholderEsperado: "State/Province (Only certain countries) *",
    },
    {
      nombre: "Codigo cedular del pais",
      selector: 'select[name="phoneCountryCode"]',
      tipo: "select",
      valor: "Colombia (+57)",
      placeholderEsperado: "Phone Country Code *",
    },
    {
      nombre: "Celular",
      selector: 'input[name="Phone"]',
      tipo: "text",
      valor: "3005005050",
      placeholderEsperado: "Phone Number *",
    },
    {
      nombre: "Año de preferencia para comenzar",
      selector: 'select[name="ie_estimateddateofadmissiontoie"]',
      tipo: "select",
      placeholderEsperado: "Planned entry date *",
    },
    {
      nombre: "Autorización de IE",
      selector: 'input[name="mkto_gdprc22"]',
      tipo: "checkbox",
    }
  ],
  "EN - Embed - Tipo 3 - Summer UNI - Program select - Whatsapp": [
    {
      nombre: "Nombres",
      selector: 'input[name="FirstName"]',
      tipo: "text",
      valor: "Ñoño",
      validacion: {
        muestrasInvalidas: ["Omni123", "Omni213!@#", "@ / \\ ? ! # % $ * + ' : ;  () [] {}"],
      },
      placeholderEsperado: "First Name *",
    },
    {
      nombre: "Apellidos",
      selector: 'input[name="MiddleName"]',
      tipo: "text",
      valor: "Pérez",
      validacion: {
        muestrasInvalidas: ["Omni123", "Omni213!@#", "@ / \\ ? ! # % $ * + ' : ;  () [] {}"],
      },
      placeholderEsperado: "Last Name *",
    },
    {
      nombre: "Email",
      selector: 'input[name="Email"]',
      tipo: "email",
      placeholderEsperado: "Email *",
    },
    {
      nombre: "Pais Colombia",
      selector: 'select[name="ie_countryid"]',
      tipo: "select",
      valor: "Colombia",
      placeholderEsperado: "Current Country/Territory of Residence *",
    },
    {
      nombre: "Pais Mexico",
      selector: 'select[name="ie_countryid"]',
      tipo: "select",
      valor: "Mexico",
    },
    {
      nombre: "Genero",
      selector: 'select[name="ie_genderidentity"]',
      tipo: "select",
      placeholderEsperado: "Gender Identity *",
    },
    {
      nombre: "Provincia/Region",
      selector: 'select[name="ie_provinceregionid"]',
      tipo: "select",
      valor: "Aguascalientes",
      placeholderEsperado: "State/Province (Only certain countries) *",
    },
    {
      nombre: "Codigo cedular del pais",
      selector: 'select[name="phoneCountryCode"]',
      tipo: "select",
      valor: "Colombia (+57)",
      placeholderEsperado: "Phone Country Code *",
    },
    {
      nombre: "Celular",
      selector: 'input[name="Phone"]',
      tipo: "text",
      valor: "3005005050",
      placeholderEsperado: "Phone Number *",
    },
    {
      nombre: "Año de preferencia para comenzar",
      selector: 'select[name="ie_estimateddateofadmissiontoie"]',
      tipo: "select",
      placeholderEsperado: "Planned entry date *",
    },
    {
      nombre: "Autorización de IE",
      selector: 'input[name="mkto_gdprc22"]',
      tipo: "checkbox",
    }
  ],
  "EN - Embed - Tipo 3 - Summer PRE- UNI - Program select optional Phone number - BAC": [
    {
      nombre: "Nombres",
      selector: 'input[name="FirstName"]',
      tipo: "text",
      valor: "Ñoño",
      validacion: {
        muestrasInvalidas: ["Omni123", "Omni213!@#", "@ / \\ ? ! # % $ * + ' : ;  () [] {}"],
      },
      placeholderEsperado: "First Name *",
    },
    {
      nombre: "Apellidos",
      selector: 'input[name="MiddleName"]',
      tipo: "text",
      valor: "Pérez",
      validacion: {
        muestrasInvalidas: ["Omni123", "Omni213!@#", "@ / \\ ? ! # % $ * + ' : ;  () [] {}"],
      },
      placeholderEsperado: "Last Name *",
    },
    {
      nombre: "Email",
      selector: 'input[name="Email"]',
      tipo: "email",
      placeholderEsperado: "Email *",
    },
    {
      nombre: "Pais Colombia",
      selector: 'select[name="ie_countryid"]',
      tipo: "select",
      valor: "Colombia",
      placeholderEsperado: "Current Country/Territory of Residence *",
    },
    {
      nombre: "Pais Mexico",
      selector: 'select[name="ie_countryid"]',
      tipo: "select",
      valor: "Mexico",
    },
    {
      nombre: "Genero",
      selector: 'select[name="ie_genderidentity"]',
      tipo: "select",
      placeholderEsperado: "Gender Identity *",
    },
    {
      nombre: "Provincia/Region",
      selector: 'select[name="ie_provinceregionid"]',
      tipo: "select",
      valor: "Aguascalientes",
      placeholderEsperado: "State/Province (Only certain countries) *",
    },
    {
      nombre: "Codigo cedular del pais",
      selector: 'select[name="phoneCountryCode"]',
      tipo: "select",
      valor: "Colombia (+57)",
      placeholderEsperado: "Phone Country Code",
    },
    {
      nombre: "Celular",
      selector: 'input[name="Phone"]',
      tipo: "text",
      valor: "3005005050",
      placeholderEsperado: "Phone Number",
    },
    {
      nombre: "Año de preferencia para comenzar",
      selector: 'select[name="ie_estimateddateofadmissiontoie"]',
      tipo: "select",
      placeholderEsperado: "Preferred start year *",
    },
    {
      nombre: "Autorización de IE",
      selector: 'input[name="mkto_gdprc22"]',
      tipo: "checkbox",
    }
  ],
  "EN - Embed - Tipo 3 - Summer PRE- UNI - Program select optional Phone number - Whatsapp": [
    {
      nombre: "Nombres",
      selector: 'input[name="FirstName"]',
      tipo: "text",
      valor: "Ñoño",
      validacion: {
        muestrasInvalidas: ["Omni123", "Omni213!@#", "@ / \\ ? ! # % $ * + ' : ;  () [] {}"],
      },
      placeholderEsperado: "First Name *",
    },
    {
      nombre: "Apellidos",
      selector: 'input[name="MiddleName"]',
      tipo: "text",
      valor: "Pérez",
      validacion: {
        muestrasInvalidas: ["Omni123", "Omni213!@#", "@ / \\ ? ! # % $ * + ' : ;  () [] {}"],
      },
      placeholderEsperado: "Last Name *",
    },
    {
      nombre: "Email",
      selector: 'input[name="Email"]',
      tipo: "email",
      placeholderEsperado: "Email *",
    },
    {
      nombre: "Pais Colombia",
      selector: 'select[name="ie_countryid"]',
      tipo: "select",
      valor: "Colombia",
      placeholderEsperado: "Current Country/Territory of Residence *",
    },
    {
      nombre: "Pais Mexico",
      selector: 'select[name="ie_countryid"]',
      tipo: "select",
      valor: "Mexico",
    },
    {
      nombre: "Genero",
      selector: 'select[name="ie_genderidentity"]',
      tipo: "select",
      placeholderEsperado: "Gender Identity *",
    },
    {
      nombre: "Provincia/Region",
      selector: 'select[name="ie_provinceregionid"]',
      tipo: "select",
      valor: "Aguascalientes",
      placeholderEsperado: "State/Province (Only certain countries) *",
    },
    {
      nombre: "Codigo cedular del pais",
      selector: 'select[name="phoneCountryCode"]',
      tipo: "select",
      valor: "Colombia (+57)",
      placeholderEsperado: "Phone Country Code",
    },
    {
      nombre: "Celular",
      selector: 'input[name="Phone"]',
      tipo: "text",
      valor: "3005005050",
      placeholderEsperado: "Phone Number",
    },
    {
      nombre: "Año de preferencia para comenzar",
      selector: 'select[name="ie_estimateddateofadmissiontoie"]',
      tipo: "select",
      placeholderEsperado: "Preferred start year *",
    },
    {
      nombre: "Autorización de IE",
      selector: 'input[name="mkto_gdprc22"]',
      tipo: "checkbox",
    }
  ],
  "ES - Embed - AD - Program select - BAC": [
    {
      nombre: "Nombres",
      selector: 'input[name="FirstName"]',
      tipo: "text",
      valor: "Ñoño",
      validacion: {
        muestrasInvalidas: ["Omni123", "Omni213!@#", "@ / \\ ? ! # % $ * + ' : ;  () [] {}"],
      },
      placeholderEsperado: "Nombre *",
    },
    {
      nombre: "Apellidos",
      selector: 'input[name="MiddleName"]',
      tipo: "text",
      valor: "Pérez",
      validacion: {
        muestrasInvalidas: ["Omni123", "Omni213!@#", "@ / \\ ? ! # % $ * + ' : ;  () [] {}"],
      },
      placeholderEsperado: "Apellidos *",
    },
    {
      nombre: "Email",
      selector: 'input[name="Email"]',
      tipo: "email",
      placeholderEsperado: "Email *",
    },
    {
      nombre: "Pais Colombia",
      selector: 'select[name="ie_countryid"]',
      tipo: "select",
      valor: "Colombia",
      placeholderEsperado: "País/Territorio de residencia actual *",
    },
    {
      nombre: "Pais Mexico",
      selector: 'select[name="ie_countryid"]',
      tipo: "select",
      valor: "Mexico",
    },
    {
      nombre: "Genero",
      selector: 'select[name="ie_genderidentity"]',
      tipo: "select",
      placeholderEsperado: "Identidad de género *",
    },
    {
      nombre: "Provincia/Region",
      selector: 'select[name="ie_provinceregionid"]',
      tipo: "select",
      valor: "Aguascalientes",
      placeholderEsperado: "Estado/Provincia (Sólo algunos países) *",
    },
    {
      nombre: "Codigo cedular del pais",
      selector: 'select[name="phoneCountryCode"]',
      tipo: "select",
      valor: "Colombia (+57)",
      placeholderEsperado: "Código de teléfono *",
    },
    {
      nombre: "Celular",
      selector: 'input[name="Phone"]',
      tipo: "text",
      valor: "3005005050",
      placeholderEsperado: "Número de teléfono *",
    },
    {
      nombre: "Años de experiencia",
      selector: 'input[name="ie_yearsofexperience"]',
      tipo: "text",
      valor: "30",
      placeholderEsperado: "Años de experiencia *",
    },
    {
      nombre: "Compañia",
      selector: 'input[name="ie_company"]',
      tipo: "text",
      valor: "Omni pro",
      placeholderEsperado: "Compañía *",
    },
    {
      nombre: "Puesto de trabajo",
      selector: 'input[name="ie_currentposition"]',
      tipo: "text",
      valor: "QA Automation",
      placeholderEsperado: "Puesto de trabajo *",
    },
    {
      nombre: "Autorización de IE",
      selector: 'input[name="mkto_gdprc22"]',
      tipo: "checkbox",
    }
  ],
  "EN - Embed - AD - Program select": [
    {
      nombre: "Nombres",
      selector: 'input[name="FirstName"]',
      tipo: "text",
      valor: "Ñoño",
      validacion: {
        muestrasInvalidas: ["Omni123", "Omni213!@#", "@ / \\ ? ! # % $ * + ' : ;  () [] {}"],
      },
      placeholderEsperado: "First Name *",
    },
    {
      nombre: "Apellidos",
      selector: 'input[name="MiddleName"]',
      tipo: "text",
      valor: "Pérez",
      validacion: {
        muestrasInvalidas: ["Omni123", "Omni213!@#", "@ / \\ ? ! # % $ * + ' : ;  () [] {}"],
      },
      placeholderEsperado: "Last Name *",
    },
    {
      nombre: "Email",
      selector: 'input[name="Email"]',
      tipo: "email",
      placeholderEsperado: "Email *",
    },
    {
      nombre: "Pais Colombia",
      selector: 'select[name="ie_countryid"]',
      tipo: "select",
      valor: "Colombia",
      placeholderEsperado: "Current Country/Territory of Residence *",
    },
    {
      nombre: "Pais Mexico",
      selector: 'select[name="ie_countryid"]',
      tipo: "select",
      valor: "Mexico",
    },
    {
      nombre: "Genero",
      selector: 'select[name="ie_genderidentity"]',
      tipo: "select",
      placeholderEsperado: "Gender Identity *",
    },
    {
      nombre: "Provincia/Region",
      selector: 'select[name="ie_provinceregionid"]',
      tipo: "select",
      valor: "Aguascalientes",
      placeholderEsperado: "State/Province (Only certain countries) *",
    },
    {
      nombre: "Codigo cedular del pais",
      selector: 'select[name="phoneCountryCode"]',
      tipo: "select",
      valor: "Colombia (+57)",
      placeholderEsperado: "Phone Country Code *",
    },
    {
      nombre: "Celular",
      selector: 'input[name="Phone"]',
      tipo: "text",
      valor: "3005005050",
      placeholderEsperado: "Phone Number *",
    },
    {
      nombre: "Autorización de IE",
      selector: 'input[name="mkto_gdprc22"]',
      tipo: "checkbox",
    }
  ],
  "ES - Embed - AD - Program select": [
    {
      nombre: "Nombres",
      selector: 'input[name="FirstName"]',
      tipo: "text",
      valor: "Ñoño",
      validacion: {
        muestrasInvalidas: ["Omni123", "Omni213!@#", "@ / \\ ? ! # % $ * + ' : ;  () [] {}"],
      },
      placeholderEsperado: "Nombre *",
    },
    {
      nombre: "Apellidos",
      selector: 'input[name="MiddleName"]',
      tipo: "text",
      valor: "Pérez",
      validacion: {
        muestrasInvalidas: ["Omni123", "Omni213!@#", "@ / \\ ? ! # % $ * + ' : ;  () [] {}"],
      },
      placeholderEsperado: "Apellidos *",
    },
    {
      nombre: "Email",
      selector: 'input[name="Email"]',
      tipo: "email",
      placeholderEsperado: "Email *",
    },
    {
      nombre: "Pais Colombia",
      selector: 'select[name="ie_countryid"]',
      tipo: "select",
      valor: "Colombia",
      placeholderEsperado: "País/Territorio de residencia actual *",
    },
    {
      nombre: "Pais Mexico",
      selector: 'select[name="ie_countryid"]',
      tipo: "select",
      valor: "Mexico",
    },
    {
      nombre: "Genero",
      selector: 'select[name="ie_genderidentity"]',
      tipo: "select",
      placeholderEsperado: "Identidad de género *",
    },
    {
      nombre: "Provincia/Region",
      selector: 'select[name="ie_provinceregionid"]',
      tipo: "select",
      valor: "Aguascalientes",
      placeholderEsperado: "Estado/Provincia (Sólo algunos países) *",
    },
    {
      nombre: "Codigo cedular del pais",
      selector: 'select[name="phoneCountryCode"]',
      tipo: "select",
      valor: "Colombia (+57)",
      placeholderEsperado: "Código de teléfono *",
    },
    {
      nombre: "Celular",
      selector: 'input[name="Phone"]',
      tipo: "text",
      valor: "3005005050",
      placeholderEsperado: "Número de teléfono *",
    },
    {
      nombre: "Años de experiencia",
      selector: 'input[name="ie_yearsofexperience"]',
      tipo: "text",
      valor: "30",
      placeholderEsperado: "Años de experiencia *",
    },
    {
      nombre: "Compañia",
      selector: 'input[name="ie_company"]',
      tipo: "text",
      valor: "Omni pro",
      placeholderEsperado: "Compañía *",
    },
    {
      nombre: "Puesto de trabajo",
      selector: 'input[name="ie_currentposition"]',
      tipo: "text",
      valor: "QA Automation",
      placeholderEsperado: "Puesto de trabajo *",
    },
    {
      nombre: "Autorización de IE",
      selector: 'input[name="mkto_gdprc22"]',
      tipo: "checkbox",
    }
  ],
  "ES - Embed - PD, PE, Bootcamp, IOPS - Program select - BAC": [
    {
      nombre: "Nombres",
      selector: 'input[name="FirstName"]',
      tipo: "text",
      valor: "Ñoño",
      validacion: {
        muestrasInvalidas: ["Omni123", "Omni213!@#", "@ / \\ ? ! # % $ * + ' : ;  () [] {}"],
      },
      placeholderEsperado: "Nombre *",
    },
    {
      nombre: "Apellidos",
      selector: 'input[name="MiddleName"]',
      tipo: "text",
      valor: "Pérez",
      validacion: {
        muestrasInvalidas: ["Omni123", "Omni213!@#", "@ / \\ ? ! # % $ * + ' : ;  () [] {}"],
      },
      placeholderEsperado: "Apellidos *",
    },
    {
      nombre: "Email",
      selector: 'input[name="Email"]',
      tipo: "email",
      placeholderEsperado: "Email *",
    },
    {
      nombre: "Pais Colombia",
      selector: 'select[name="ie_countryid"]',
      tipo: "select",
      valor: "Colombia",
      placeholderEsperado: "País/Territorio de residencia actual *",
    },
    {
      nombre: "Pais Mexico",
      selector: 'select[name="ie_countryid"]',
      tipo: "select",
      valor: "Mexico",
    },
    {
      nombre: "Genero",
      selector: 'select[name="ie_genderidentity"]',
      tipo: "select",
      placeholderEsperado: "Identidad de género *",
    },
    {
      nombre: "Provincia/Region",
      selector: 'select[name="ie_provinceregionid"]',
      tipo: "select",
      valor: "Aguascalientes",
      placeholderEsperado: "Estado/Provincia (Sólo algunos países) *",
    },
    {
      nombre: "Codigo cedular del pais",
      selector: 'select[name="phoneCountryCode"]',
      tipo: "select",
      valor: "Colombia (+57)",
      placeholderEsperado: "Código de teléfono *",
    },
    {
      nombre: "Celular",
      selector: 'input[name="Phone"]',
      tipo: "text",
      valor: "3005005050",
      placeholderEsperado: "Número de teléfono *",
    },
    {
      nombre: "Años de experiencia",
      selector: 'input[name="ie_yearsofexperience"]',
      tipo: "text",
      valor: "30",
      placeholderEsperado: "Años de experiencia *",
    },
    {
      nombre: "Compañia",
      selector: 'input[name="ie_company"]',
      tipo: "text",
      valor: "Omni pro",
      placeholderEsperado: "Compañía *",
    },
    {
      nombre: "Puesto de trabajo",
      selector: 'input[name="ie_currentposition"]',
      tipo: "text",
      valor: "QA Automation",
      placeholderEsperado: "Puesto de trabajo *",
    },
    {
      nombre: "Autorización de IE",
      selector: 'input[name="mkto_gdprc22"]',
      tipo: "checkbox",
    }
  ],
  "EN - Embed - PD, PE, Bootcamp, IOPS - Program picklist": [
    {
      nombre: "Nombres",
      selector: 'input[name="FirstName"]',
      tipo: "text",
      valor: "Ñoño",
      validacion: {
        muestrasInvalidas: ["Omni123", "Omni213!@#", "@ / \\ ? ! # % $ * + ' : ;  () [] {}"],
      },
      placeholderEsperado: "First Name *",
    },
    {
      nombre: "Apellidos",
      selector: 'input[name="MiddleName"]',
      tipo: "text",
      valor: "Pérez",
      validacion: {
        muestrasInvalidas: ["Omni123", "Omni213!@#", "@ / \\ ? ! # % $ * + ' : ;  () [] {}"],
      },
      placeholderEsperado: "Last Name *",
    },
    {
      nombre: "Email",
      selector: 'input[name="Email"]',
      tipo: "email",
      placeholderEsperado: "Email *",
    },
    {
      nombre: "Pais Colombia",
      selector: 'select[name="ie_countryid"]',
      tipo: "select",
      valor: "Colombia",
      placeholderEsperado: "Current Country/Territory of Residence *",
    },
    {
      nombre: "Pais Mexico",
      selector: 'select[name="ie_countryid"]',
      tipo: "select",
      valor: "Mexico",
    },
    {
      nombre: "Genero",
      selector: 'select[name="ie_genderidentity"]',
      tipo: "select",
      placeholderEsperado: "Gender Identity *",
    },
    {
      nombre: "Provincia/Region",
      selector: 'select[name="ie_provinceregionid"]',
      tipo: "select",
      valor: "Aguascalientes",
      placeholderEsperado: "State/Province (Only certain countries) *",
    },
    {
      nombre: "Codigo cedular del pais",
      selector: 'select[name="phoneCountryCode"]',
      tipo: "select",
      valor: "Colombia (+57)",
      placeholderEsperado: "Phone Country Code *",
    },
    {
      nombre: "Celular",
      selector: 'input[name="Phone"]',
      tipo: "text",
      valor: "3005005050",
      placeholderEsperado: "Phone Number *",
    },
    {
      nombre: "Programa de interés",
      selector: 'select[name="ie_programmarketoid"]',
      tipo: "select",
      placeholderEsperado: "Program of interest *",
    },
    {
      nombre: "Autorización de IE",
      selector: 'input[name="mkto_gdprc22"]',
      tipo: "checkbox",
    }
  ],
  "EN - Embed - PD, PE, Bootcamp, IOPS - Program select": [
    {
      nombre: "Nombres",
      selector: 'input[name="FirstName"]',
      tipo: "text",
      valor: "Ñoño",
      validacion: {
        muestrasInvalidas: ["Omni123", "Omni213!@#", "@ / \\ ? ! # % $ * + ' : ;  () [] {}"],
      },
      placeholderEsperado: "First Name *",
    },
    {
      nombre: "Apellidos",
      selector: 'input[name="MiddleName"]',
      tipo: "text",
      valor: "Pérez",
      validacion: {
        muestrasInvalidas: ["Omni123", "Omni213!@#", "@ / \\ ? ! # % $ * + ' : ;  () [] {}"],
      },
      placeholderEsperado: "Last Name *",
    },
    {
      nombre: "Email",
      selector: 'input[name="Email"]',
      tipo: "email",
      placeholderEsperado: "Email *",
    },
    {
      nombre: "Pais Colombia",
      selector: 'select[name="ie_countryid"]',
      tipo: "select",
      valor: "Colombia",
      placeholderEsperado: "Current Country/Territory of Residence *",
    },
    {
      nombre: "Pais Mexico",
      selector: 'select[name="ie_countryid"]',
      tipo: "select",
      valor: "Mexico",
    },
    {
      nombre: "Genero",
      selector: 'select[name="ie_genderidentity"]',
      tipo: "select",
      placeholderEsperado: "Gender Identity *",
    },
    {
      nombre: "Provincia/Region",
      selector: 'select[name="ie_provinceregionid"]',
      tipo: "select",
      valor: "Aguascalientes",
      placeholderEsperado: "State/Province (Only certain countries) *",
    },
    {
      nombre: "Codigo cedular del pais",
      selector: 'select[name="phoneCountryCode"]',
      tipo: "select",
      valor: "Colombia (+57)",
      placeholderEsperado: "Phone Country Code *",
    },
    {
      nombre: "Celular",
      selector: 'input[name="Phone"]',
      tipo: "text",
      valor: "3005005050",
      placeholderEsperado: "Phone Number *",
    },
    {
      nombre: "Autorización de IE",
      selector: 'input[name="mkto_gdprc22"]',
      tipo: "checkbox",
    }
  ],
  "ES - Embed - PD, PE, Bootcamp, IOPS - Program select": [
    {
      nombre: "Nombres",
      selector: 'input[name="FirstName"]',
      tipo: "text",
      valor: "Ñoño",
      validacion: {
        muestrasInvalidas: ["Omni123", "Omni213!@#", "@ / \\ ? ! # % $ * + ' : ;  () [] {}"],
      },
      placeholderEsperado: "Nombre *",
    },
    {
      nombre: "Apellidos",
      selector: 'input[name="MiddleName"]',
      tipo: "text",
      valor: "Pérez",
      validacion: {
        muestrasInvalidas: ["Omni123", "Omni213!@#", "@ / \\ ? ! # % $ * + ' : ;  () [] {}"],
      },
      placeholderEsperado: "Apellidos *",
    },
    {
      nombre: "Email",
      selector: 'input[name="Email"]',
      tipo: "email",
      placeholderEsperado: "Email *",
    },
    {
      nombre: "Pais Colombia",
      selector: 'select[name="ie_countryid"]',
      tipo: "select",
      valor: "Colombia",
      placeholderEsperado: "País/Territorio de residencia actual *",
    },
    {
      nombre: "Pais Mexico",
      selector: 'select[name="ie_countryid"]',
      tipo: "select",
      valor: "Mexico",
    },
    {
      nombre: "Genero",
      selector: 'select[name="ie_genderidentity"]',
      tipo: "select",
      placeholderEsperado: "Identidad de género *",
    },
    {
      nombre: "Provincia/Region",
      selector: 'select[name="ie_provinceregionid"]',
      tipo: "select",
      valor: "Aguascalientes",
      placeholderEsperado: "Estado/Provincia (Sólo algunos países) *",
    },
    {
      nombre: "Codigo cedular del pais",
      selector: 'select[name="phoneCountryCode"]',
      tipo: "select",
      valor: "Colombia (+57)",
      placeholderEsperado: "Código de teléfono *",
    },
    {
      nombre: "Celular",
      selector: 'input[name="Phone"]',
      tipo: "text",
      valor: "3005005050",
      placeholderEsperado: "Número de teléfono *",
    },
    {
      nombre: "Autorización de IE",
      selector: 'input[name="mkto_gdprc22"]',
      tipo: "checkbox",
    }
  ]
};

export const obtenerCampos = (tipoFormulario: string): DefinicionCampoFormulario[] => {
  return configuracionFormularios[tipoFormulario];
};
